export const FIND_PRODUCTS_BY_CATEGORY_REQUEST = 'FIND_PRODUCTS_BY_CATEGORY_REQUEST'
export const FIND_PRODUCT_BY_CATEGORY_SUCCESS = 'FIND_PRODUCT_BY_CATEGORY_SUCCESS'
export const FIND_PRODUCT_BY_CATEGORY_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE'

export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const FETCH_HOMEPAGE_CATEGORY_PRODUCTS_REQUEST = "FETCH_HOMEPAGE_CATEGORY_PRODUCTS_REQUEST";
export const FETCH_HOMEPAGE_CATEGORY_PRODUCTS_SUCCESS = "FETCH_HOMEPAGE_CATEGORY_PRODUCTS_SUCCESS";
export const FETCH_HOMEPAGE_CATEGORY_PRODUCTS_FAILURE = "FETCH_HOMEPAGE_CATEGORY_PRODUCTS_FAILURE";
