// src/redux/Auth/authActionTypes.js

// 🔹 REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// 🔹 LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// 🔹 OTP Verification
export const SEND_VERIFY_OTP_REQUEST = "SEND_VERIFY_OTP_REQUEST";
export const SEND_VERIFY_OTP_SUCCESS = "SEND_VERIFY_OTP_SUCCESS";
export const SEND_VERIFY_OTP_FAILURE = "SEND_VERIFY_OTP_FAILURE";

export const CONFIRM_VERIFY_OTP_REQUEST = "CONFIRM_VERIFY_OTP_REQUEST";
export const CONFIRM_VERIFY_OTP_SUCCESS = "CONFIRM_VERIFY_OTP_SUCCESS";
export const CONFIRM_VERIFY_OTP_FAILURE = "CONFIRM_VERIFY_OTP_FAILURE";

// 🔹 Forgot Password (Reset via OTP)
export const SEND_RESET_OTP_REQUEST = "SEND_RESET_OTP_REQUEST";
export const SEND_RESET_OTP_SUCCESS = "SEND_RESET_OTP_SUCCESS";
export const SEND_RESET_OTP_FAILURE = "SEND_RESET_OTP_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

// 🔹 LOGOUT
export const LOGOUT = "LOGOUT";
